package main

import (
	"fmt"
	"os"
	"strings"
)

// writeConflicts renders the review table. It is regenerated wholesale each
// run, so a disagreement somebody resolved drops off by itself.
func writeConflicts(path string, cs []conflict) error {
	var b strings.Builder
	b.WriteString("# presetgen conflicts\n\n")
	b.WriteString("Generated by tools/presetgen. Do not hand-edit.\n\n")
	if len(cs) == 0 {
		b.WriteString("The two upstream registries agree on every field.\n")
		return os.WriteFile(path, []byte(b.String()), 0o644)
	}
	b.WriteString("| Preset | Field | Winner | Winning value | Loser | Losing value |\n")
	b.WriteString("|---|---|---|---|---|---|\n")
	for _, c := range cs {
		fmt.Fprintf(&b, "| %s | %s | %s | `%s` | %s | `%s` |\n",
			c.ID, c.Field, c.Winner, c.WinnerValue, c.Loser, c.LoserValue)
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}
