package main

import (
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"
)

// validPresetID bounds what may appear as a YAML mapping key in the manifest.
// writeProvenance builds the file by string concatenation, so an id carrying
// a YAML metacharacter would not fail loudly -- it would just produce a
// manifest Provenance() silently misparses.
var validPresetID = regexp.MustCompile(`^[a-z0-9._-]+$`)

// manifestMeta stamps the run. Without the upstream SHAs nothing answers
// whether a field changed because upstream moved or because a scraper did.
type manifestMeta struct {
	OmniRouteSHA  string
	NineRouterSHA string
	GeneratedAt   string
}

func writeProvenance(path string, m merged, meta manifestMeta) error {
	var b strings.Builder
	b.WriteString("# Generated by tools/presetgen. Do not hand-edit.\n")
	b.WriteString("#\n")
	b.WriteString("# Which upstream supplied each structural field. Price provenance is a\n")
	b.WriteString("# runtime fact and lives in the models.price_source column instead.\n")
	fmt.Fprintf(&b, "omniroute_sha: %s\n", meta.OmniRouteSHA)
	fmt.Fprintf(&b, "ninerouter_sha: %s\n", meta.NineRouterSHA)
	fmt.Fprintf(&b, "generated_at: %s\n", meta.GeneratedAt)
	b.WriteString("presets:\n")

	ids := make([]string, 0, len(m.Origins))
	for id := range m.Origins {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	for _, id := range ids {
		if !validPresetID.MatchString(id) {
			return fmt.Errorf("writeProvenance: id %q contains characters outside [a-z0-9._-]", id)
		}
		fmt.Fprintf(&b, "  %s:\n", id)
		origins := append([]fieldOrigin(nil), m.Origins[id]...)
		sort.Slice(origins, func(i, j int) bool { return origins[i].Field < origins[j].Field })
		for _, o := range origins {
			fmt.Fprintf(&b, "    %s: %s\n", o.Field, o.Source)
		}
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}
