package catalog

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"regexp"
	"sync"
)

// freeCatalogJSON is the curated free-tier catalog transcribed from OmniRoute
// by tools/presetgen.
//
//go:embed free_models.json
var freeCatalogJSON []byte

// FreeCatalog is the list of models a provider's free tier documents, keyed by
// preset id then model id, with the kind of free each one is.
//
// It exists because free-tier membership cannot be derived. A price index
// records what a model costs on the paid tier; whether a vendor's free tier
// covers it is a property of the account, published in the vendor's own docs
// and nowhere in its API. Groq is the case that proves it: every model it
// serves carries a per-token price, and thirteen of them are on its free tier.
type FreeCatalog struct {
	// CuratedAt is the day the upstream catalog was last checked against
	// provider documentation. Printed rather than inferred from a file
	// timestamp, which a rebuild would reset to today.
	CuratedAt string `json:"curated_at"`
	// Providers maps preset id -> model id -> freeType.
	Providers map[string]map[string]string `json:"providers"`
}

// freeTypeDiscontinued marks a free tier the provider has withdrawn. The
// upstream catalog keeps those rows for the history; a withdrawn tier is not
// one an import filter may count on.
const freeTypeDiscontinued = "discontinued"

var (
	freeOnce    sync.Once
	freeCatalog FreeCatalog
)

// FreeModels is the embedded curated catalog.
//
// A parse failure degrades to an empty catalog rather than panicking, for the
// same reason FallbackDoc does: the file is generated, its shape is asserted
// by this package's tests, and a gateway that refuses to boot over it would be
// a worse outcome than one whose free filter falls back to prices alone.
func FreeModels() FreeCatalog {
	freeOnce.Do(func() {
		if err := json.Unmarshal(freeCatalogJSON, &freeCatalog); err != nil {
			freeCatalog = FreeCatalog{}
		}
	})
	return freeCatalog
}

// Covers reports whether the provider's free tier documents this model.
func (c FreeCatalog) Covers(presetID, modelID string) bool {
	kind, ok := c.Providers[presetID][modelID]
	return ok && kind != freeTypeDiscontinued
}

// ModelsFor lists the models documented free for one preset, discontinued
// tiers excluded. Nil for a provider the catalog has never covered, which is a
// different fact from one whose free tier has been withdrawn.
func (c FreeCatalog) ModelsFor(presetID string) []string {
	models := c.Providers[presetID]
	if len(models) == 0 {
		return nil
	}
	out := make([]string, 0, len(models))
	for id, kind := range models {
		if kind != freeTypeDiscontinued {
			out = append(out, id)
		}
	}
	return out
}

// freeEntry matches one line of OmniRoute's FREE_MODEL_BUDGETS. Only the three
// fields darkrouter decides on are read: which provider, which model, and what
// kind of free it is. The quota, pool key and terms verdict beside them answer
// questions darkrouter does not ask.
var freeEntry = regexp.MustCompile(
	`\{ provider: "([^"]+)", modelId: "([^"]+)".*?freeType: "([^"]+)"`)

var curatedAt = regexp.MustCompile(`FREE_CATALOG_CURATED_AT = "([^"]+)"`)

// ParseFreeCatalog reads the upstream catalogue's TypeScript source.
//
// A regex over source rather than a JSON parse because that is the form
// upstream publishes: the list is a literal in a .ts file, and asking them for
// a machine-readable export is not a dependency darkrouter can create. The
// shape is uniform -- one object literal per line, generated by their own
// tooling -- and a change to it fails loudly here rather than silently
// yielding a catalogue with nothing in it.
//
// Shared with tools/presetgen so the file embedded at build time and the one
// fetched at runtime are read by the same code.
func ParseFreeCatalog(raw []byte) (FreeCatalog, error) {
	out := FreeCatalog{Providers: map[string]map[string]string{}}
	if m := curatedAt.FindSubmatch(raw); m != nil {
		out.CuratedAt = string(m[1])
	}
	for _, m := range freeEntry.FindAllSubmatch(raw, -1) {
		provider, model, kind := string(m[1]), string(m[2]), string(m[3])
		if out.Providers[provider] == nil {
			out.Providers[provider] = map[string]string{}
		}
		out.Providers[provider][model] = kind
	}
	if len(out.Providers) == 0 {
		return FreeCatalog{}, fmt.Errorf("free catalogue held no entries")
	}
	return out, nil
}
