// Generated by tools/presetgen. Do not edit.
//
// Which presets have a logo file in web/public/providers, so ProviderIcon can
// reach for one without a request that might 404. A preset absent here has
// either a brand mark from @lobehub/icons or the monogram, in that order.
//
// Mono marks an SVG drawn only in black ink, which the dark canvas inverts:
// the file carries its own colour and cannot adapt the way a currentColor mark
// does, and a black mark on a near-black tile is an empty tile.

export type ProviderAsset = { file: string; mono?: boolean }

export const PROVIDER_ASSETS: Record<string, ProviderAsset> = {
  "arcee-ai": { file: "arcee-ai.svg" },
  "auggie": { file: "auggie.svg" },
  "bluesminds": { file: "bluesminds.svg" },
  "bytez": { file: "bytez.svg" },
  "charm-hyper": { file: "charm-hyper.svg" },
  "chutes": { file: "chutes.svg" },
  "crof": { file: "crof.svg" },
  "dgrid": { file: "dgrid.svg" },
  "dit": { file: "dit.svg" },
  "factory": { file: "factory.svg" },
  "freeaiapikey": { file: "freeaiapikey.svg" },
  "freemodel-dev": { file: "freemodel-dev.svg" },
  "galadriel": { file: "galadriel.svg" },
  "gitlawb": { file: "gitlawb.svg" },
  "hcnsec": { file: "hcnsec.svg" },
  "heroku": { file: "heroku.svg" },
  "kenari": { file: "kenari.svg" },
  "llm7": { file: "llm7.svg" },
  "monsterapi": { file: "monsterapi.svg" },
  "nube": { file: "nube.svg" },
  "openadapter": { file: "openadapter.svg" },
  "opper": { file: "opper.svg" },
  "orcarouter": { file: "orcarouter.svg" },
  "ovhcloud": { file: "ovhcloud.svg" },
  "pioneer": { file: "pioneer.svg" },
  "publicai": { file: "publicai.svg" },
  "requesty": { file: "requesty.svg" },
  "sparkdesk": { file: "sparkdesk.svg" },
  "sumopod": { file: "sumopod.svg" },
  "tokenrouter": { file: "tokenrouter.svg" },
  "uncloseai": { file: "uncloseai.svg" },
  "vllm": { file: "vllm.svg" },
  "wafer": { file: "wafer.svg" },
  "x5lab": { file: "x5lab.svg" },
  "xinference": { file: "xinference.svg" },
}
